export const HR_CONSTANTS = {
  MAX_LEAVE_DAYS: 90,
  DEFAULT_LEAVE_BALANCE: 30,
  LEAVE_CARRYOVER_LIMIT: 10,
  PAYROLL_PROCESSING_DAY: 25,
  PRIME_APPROVAL_LIMIT: 5000,
  CREDIT_APPROVAL_LIMIT: 100000,
} as const;
